
// citys.js
export const citys = [
    { value: "BOGOTÁ", label: "BOGOTÁ D.C." },
    { value: "MEDELLÍN", label: "MEDELLÍN" },
    { value: "CALI", label: "CALI" },
    { value: "BARRANQUILLA", label: "BARRANQUILLA" },
    { value: "CARTAGENA", label: "CARTAGENA" },
    { value: "CUCUTA", label: "CUCUTA" },
    { value: "BUCARAMANGA", label: "BUCARAMANGA" },
    { value: "VILLAVICENCIO", label: "VILLAVICENCIO" },
    { value: "IBAGUÉ", label: "IBAGUÉ" },
    { value: "SANTA", label: "SANTA MARTA" },
    { value: "PEREIRA", label: "PEREIRA" },
    { value: "MANIZALES", label: "MANIZALES" },
    { value: "MONTERÍA", label: "MONTERÍA" },
    { value: "NEIVA", label: "NEIVA" },
    { value: "PASTO", label: "PASTO" },
    { value: "ARMENIA", label: "ARMENIA" },
    { value: "POPAYÁN", label: "POPAYÁN" },
    { value: "VALLEDUPAR", label: "VALLEDUPAR" },
    { value: "SINCELEJO", label: "SINCELEJO" },
    { value: "RIOHACHA", label: "RIOHACHA" },
    { value: "TUNJA", label: "TUNJA" },
    { value: "YOPAL", label: "YOPAL" },
    { value: "QUIBDÓ", label: "QUIBDÓ" },
    { value: "FLORENCIA", label: "FLORENCIA" },
    { value: "LETICIA", label: "LETICIA" },
    { value: "MITÚ", label: "MITÚ" },
    { value: "SAN", label: "SAN ANDRÉS" },
    { value: "PUERTO", label: "PUERTO CARREÑO" },
    { value: "MOCOA", label: "MOCOA" },
  ];
  